version: "3.2"

services:
  db:
    container_name: db
    image: rethinkdb:2.4.0
    volumes:
      - ./data/:/data/rethinkdb_data
    command: rethinkdb -d /data/rethinkdb_data --bind all
    ports:
      - "29015:29015"
      - "28015:28015"
      - "8080:8080"
