version: "3.2"

services:
  node_1:
    container_name: node_1
    image: cockroachdb/cockroach:v19.2.4
    volumes:
      - ./data/node_1:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
        - "26257:26257"
        - "8080:8080"